-- MySQL Script generated by MySQL Workbench
-- Thu Feb  6 11:50:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RECIPEMANAGER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RECIPEMANAGER
-- -----------------------------------------------------
drop schema `RECIPEMANAGER`;
CREATE SCHEMA IF NOT EXISTS `RECIPEMANAGER` DEFAULT CHARACTER SET utf8 ;
USE `RECIPEMANAGER` ;

-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Ruolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Ruolo` (
  `idRuolo` INT NOT NULL AUTO_INCREMENT,
  `nomeRuolo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRuolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(90),
  `username` VARCHAR(90),
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `dataDiNAscita` DATE NULL,
  `cellulare` VARCHAR(18) NULL,
  `Ruolo_idRuolo` INT NOT NULL,
  PRIMARY KEY (`idUtente`),
  INDEX `fk_Utente_Ruolo1_idx` (`Ruolo_idRuolo` ASC) VISIBLE,
  CONSTRAINT `fk_Utente_Ruolo1`
    FOREIGN KEY (`Ruolo_idRuolo`)
    REFERENCES `RECIPEMANAGER`.`Ruolo` (`idRuolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Ricetta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Ricetta` (
  `idRicetta` INT NOT NULL AUTO_INCREMENT,
  `immagine` VARCHAR(300) NOT NULL,
  `titolo` VARCHAR(100) NOT NULL,
  `descrizione` LONGTEXT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  PRIMARY KEY (`idRicetta`),
  INDEX `fk_Ricetta_Utente_idx` (`Utente_idUtente` ASC) VISIBLE,
  CONSTRAINT `fk_Ricetta_Utente`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `RECIPEMANAGER`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Ingrediente` (
  `idIngrediente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `metrica` VARCHAR(10) NOT NULL,
  `quantita` DECIMAL(3) NOT NULL,
  /*tolte le calorie*/
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Commento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Commento` (
  `idCommento` INT NOT NULL AUTO_INCREMENT,
  `voto` TINYINT(1) NULL,
  `commento` TEXT(512) NULL,
  `segnalazione` TINYINT(1) NULL,
  `Utente_idUtente` INT NOT NULL,
  `Ricetta_idRicetta` INT NOT NULL,
  PRIMARY KEY (`idCommento`),
  INDEX `fk_Commento_Utente1_idx` (`Utente_idUtente` ASC) VISIBLE,
  INDEX `fk_Commento_Ricetta1_idx` (`Ricetta_idRicetta` ASC) VISIBLE,
  CONSTRAINT `fk_Commento_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `RECIPEMANAGER`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commento_Ricetta1`
    FOREIGN KEY (`Ricetta_idRicetta`)
    REFERENCES `RECIPEMANAGER`.`Ricetta` (`idRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(45) NOT NULL,
  `descrizioneCategoria` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Ricetta_has_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Ricetta_has_Ingrediente` (
  `Ricetta_idRicetta` INT NOT NULL,
  `Ingrediente_idIngrediente` INT NOT NULL,
  PRIMARY KEY (`Ricetta_idRicetta`, `Ingrediente_idIngrediente`),
  INDEX `fk_Ricetta_has_Ingrediente_Ingrediente1_idx` (`Ingrediente_idIngrediente` ASC) VISIBLE,
  INDEX `fk_Ricetta_has_Ingrediente_Ricetta1_idx` (`Ricetta_idRicetta` ASC) VISIBLE,
  CONSTRAINT `fk_Ricetta_has_Ingrediente_Ricetta1`
    FOREIGN KEY (`Ricetta_idRicetta`)
    REFERENCES `RECIPEMANAGER`.`Ricetta` (`idRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ricetta_has_Ingrediente_Ingrediente1`
    FOREIGN KEY (`Ingrediente_idIngrediente`)
    REFERENCES `RECIPEMANAGER`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RECIPEMANAGER`.`Ricetta_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RECIPEMANAGER`.`Ricetta_has_Categoria` (
  `Ricetta_idRicetta` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Ricetta_idRicetta`, `Categoria_idCategoria`),
  INDEX `fk_Ricetta_has_Categoria_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Ricetta_has_Categoria_Ricetta1_idx` (`Ricetta_idRicetta` ASC) VISIBLE,
  CONSTRAINT `fk_Ricetta_has_Categoria_Ricetta1`
    FOREIGN KEY (`Ricetta_idRicetta`)
    REFERENCES `RECIPEMANAGER`.`Ricetta` (`idRicetta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ricetta_has_Categoria_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `RECIPEMANAGER`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
